<a href="https://colab.research.google.com/github/WittyWaithira/DataCamp_Solutions_Python/blob/master/matrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
def activation(x):
  """Sigmoid activation function"""
  return 1/(1+torch.exp(-x))


In [0]:


torch.manual_seed(7) 

#Features are 5 normal random variables

features = torch.randn((1,5))

#True weights , random normal variables

weights = torch.randn_like(features)

# a true bias

bias = torch.randn((1,1))


In [0]:
# labels from our data and true weights
y = activation(torch.sum(features*weights)+ bias)
print(y)

# method 2
y = activation((features*weights).sum()+bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [0]:
# Matrix Multiplication

y = activation(torch.mm(features,weights.view(5,1))+ bias)
print(y)

tensor([[0.1595]])
